import Foundation

/// Uniform type identifiers we care about by name.
public enum UTI {
    public static let plainText = "public.utf8-plain-text"
    public static let legacyText = "NSStringPboardType"
    public static let utf16Text = "public.utf16-external-plain-text"
    public static let rtf = "public.rtf"
    public static let rtfd = "com.apple.flat-rtfd"
    public static let html = "public.html"
    public static let url = "public.url"
    public static let urlName = "public.url-name"
    public static let fileURL = "public.file-url"
    public static let legacyFilenames = "NSFilenamesPboardType"
    public static let png = "public.png"
    public static let tiff = "public.tiff"
    public static let jpeg = "public.jpeg"
    public static let gif = "com.compuserve.gif"
    public static let heic = "public.heic"
    public static let pdf = "com.adobe.pdf"
    public static let webp = "org.webmproject.webp"
    public static let color = "com.apple.cocoa.pasteboard.color"

    public static let imageTypes: Set<String> = [png, tiff, jpeg, gif, heic, webp]

    /// Types whose mere presence means "do not record this pasteboard".
    /// Password managers and clipboard tools set these by convention.
    public static let concealed: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "de.petermaurer.TransientPasteboardType",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
    ]

    /// Types that carry no usable bytes (lazy file promises) or that we refuse
    /// to persist because they're huge and always reconstructible.
    public static let skipped: Set<String> = [
        "com.apple.pasteboard.promised-file-content-type",
        "com.apple.pasteboard.promised-file-url",
        "com.apple.pasteboard.promised-suggested-file-name",
        "com.apple.NSFilePromiseItemMetaData",
        "dyn.ah62d4rv4gu8zg55eqzxhe7562",
    ]

    /// Marker we add to our own writes so the monitor can ignore them.
    public static let internalMarker = "app.pastedeck.internal"

    public static func isImage(_ uti: String) -> Bool {
        imageTypes.contains(uti) || uti.hasPrefix("public.") && uti.contains("image")
    }
}

/// A snapshot of the system pasteboard, decoupled from AppKit so the whole
/// classification pipeline can be unit-tested.
public struct PasteboardSnapshot: Sendable {
    public struct Representation: Sendable, Equatable {
        public var uti: String
        public var data: Data

        public init(uti: String, data: Data) {
            self.uti = uti
            self.data = data
        }
    }

    public struct Item: Sendable, Equatable {
        public var representations: [Representation]

        public init(representations: [Representation]) {
            self.representations = representations
        }

        public func data(for uti: String) -> Data? {
            representations.first { $0.uti == uti }?.data
        }

        public func string(for uti: String) -> String? {
            guard let data = data(for: uti) else { return nil }
            return String(data: data, encoding: .utf8) ?? String(data: data, encoding: .utf16)
        }

        public var utis: [String] { representations.map(\.uti) }
    }

    public var items: [Item]
    public var sourceBundleID: String?
    public var sourceAppName: String
    public var capturedAt: Date

    public init(
        items: [Item],
        sourceBundleID: String? = nil,
        sourceAppName: String = "",
        capturedAt: Date = Date()
    ) {
        self.items = items
        self.sourceBundleID = sourceBundleID
        self.sourceAppName = sourceAppName
        self.capturedAt = capturedAt
    }

    public var allUTIs: Set<String> {
        Set(items.flatMap(\.utis))
    }

    public var isEmpty: Bool {
        items.allSatisfy { item in
            item.representations.allSatisfy { $0.data.isEmpty }
        }
    }

    /// True when the pasteboard is flagged as secret or transient, or is ours.
    public var shouldBeIgnored: Bool {
        let utis = allUTIs
        if utis.contains(UTI.internalMarker) { return true }
        return !utis.isDisjoint(with: UTI.concealed)
    }

    /// Convenience for the common single-item text case.
    public var plainText: String? {
        for item in items {
            if let text = item.string(for: UTI.plainText), !text.isEmpty { return text }
            if let text = item.string(for: UTI.legacyText), !text.isEmpty { return text }
            if let data = item.data(for: UTI.utf16Text),
               let text = String(data: data, encoding: .utf16), !text.isEmpty { return text }
        }
        return nil
    }
}
